#!/usr/bin/env bash
# Init script to manage manage_my_process

case "$1" in
    start)
        # Start the process
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        # Stop the process
        if [ -f "/var/run/my_process.pid" ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        # Restart the process
        if [ -f "/var/run/my_process.pid" ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
