#!/usr/bin/env bash
#This script extends previous exercise command and displays the line cointaining the bash word, this allowing you to easily get the PID of your bash process.
# You cannot use pgrep

# Shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
