#!/usr/bin/env bash
#This script displays:
	#to infinity and beyong indefinitely
	#With a sleep 2 between each iteration
	#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
